name: Upload Cleaned Sales Data to Azure Blob Storage

on:
  push:
    paths:
      - 'data/processed/sales_clean.csv'
      - '.github/workflows/upload-to-blob.yml'
  workflow_dispatch:

jobs:
  upload-to-blob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Azure CLI
        uses: azure/setup-azure@v3

      - name: Login to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload sales_clean.csv to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name etlstoragedemoalex \
            --container-name raw \
            --file data/processed/sales_clean.csv \
            --name sales_clean.csv \
            --auth-mode login
