name: Upload Cleaned Sales Data to Azure Blob Storage

on:
  push:
    paths:
      - 'data/processed/sales_clean.csv'
      - '.github/workflows/upload-to-blob.yml'
  workflow_dispatch:

jobs:
  upload-to-blob:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set Up Python 3.10 Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Ensure Azure CLI is installed
      - name: Ensure Azure CLI is Installed
        run: |
          if ! command -v az &> /dev/null
          then
            echo "Azure CLI not found, installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          else
            echo "Azure CLI is already installed."
          fi

      # Authenticate to Azure using Service Principal credentials
      - name: Azure Login via Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload the cleaned sales data CSV to Azure Blob Storage
      - name: Upload Cleaned CSV to Azure Blob Storage (Raw Container)
        run: |
          az storage blob upload \
            --account-name etlstoragedemoalex \
            --container-name raw \
            --file data/processed/sales_clean.csv \
            --name sales_clean.csv \
            --auth-mode login

